sonar.projectKey=app-reservas
sonar.projectName=app-reservas
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9001
sonar.sourceEncoding=UTF-8

sonar.sources=auth-service/src,booking-service/src,notification-service,user-service,frontend/src
sonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx
sonar.exclusions=**/node_modules/**,**/coverage/**,**/.next/**,**/*.test.js,**/*.spec.js,.github/**,qualitygate.json,backend-quality-report.md,docker-compose.sonar.yml,docker-compose.sonarqube.yml,tools/**

sonar.links.homepage=https://github.com/your-org/app-reservas
sonar.links.scm=https://github.com/your-org/app-reservas
