sonar.projectKey=app-reservas-backend
sonar.projectName=app-reservas-backend
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9001
sonar.sourceEncoding=UTF-8

sonar.sources=auth-service/src,booking-service/src,notification-service,user-service
sonar.inclusions=**/*.js
sonar.exclusions=**/node_modules/**,**/coverage/**,frontend/**,**/*.test.js,**/*.spec.js,.github/**,qualitygate.json,backend-quality-report.md,docker-compose.sonar.yml

sonar.links.homepage=https://github.com/your-org/app-reservas
sonar.links.scm=https://github.com/your-org/app-reservas
